### ISSUE TITLE
Warnings: State attribute definition missing for : n with value : Links

### ISSUE THREAD

**Issue by MatthiasBosch** [DrozmotiX/ioBroker.wled#423]
Actualy I have installed 0.6.7 of WLED Adapter and everything works fine.

In the ioBroker protocol I have 2 warnings:
**State attribute definition missing for : n with value : Links
State attribute definition missing for : n with value : Rechts**

For me it seams as if this are parameters from old versions.
Is there a possabilty to fix this?

**Comment by DutchmanNL** [comment]
Which WLED Firmware Version von do you use?

**Comment by Rushmed** [comment]
Got the same messages since FW update to 0.13.3.

**Comment by Eistee82** [comment]
Same problem, debug log:
`<html>
<body>


wled.0 | 2022-08-30 16:43:29.092 | warn | State attribute definition missing for : liveseg with value : -1
-- | -- | -- | --
wled.0 | 2022-08-30 16:43:29.092 | debug | Create_state called for : a848facea728._info.liveseg with value : -1
wled.0 | 2022-08-30 16:43:29.092 | debug | State created : liveseg : -1


</body>
</html>`

**Comment by Rushmed** [comment]
Any progress? Still got my LOG flooted by this kind of warnings.

**Comment by GrayTheZebra** [comment]
Same Problem

<html>
<body>


wled.0 | 2022-09-21 12:05:34.283 | warn | State attribute definition missing for : n with value : Regal oben
-- | -- | -- | --
wled.0 | 2022-09-21 12:05:34.260 | warn | State attribute definition missing for : n with value : Regal Mitte
wled.0 | 2022-09-21 12:05:34.233 | warn | State attribute definition missing for : n with value : Regal unten
wled.0 | 2022-09-21 12:05:34.210 | warn | State attribute definition missing for : n with value : Tisch
wled.0 | 2022-09-21 12:05:34.120 | warn | State attribute definition missing for : liveseg with value : -1


</body>
</html>

**Comment by Homeworker11** [comment]
Gleiches Problem hier auch: 
![image](https://user-images.githubusercontent.com/74406135/192240926-8a897078-91a8-494e-a9ec-f9aeb9455be4.png)
WLED version 0.13.3
Adapter Version  0.6.7

**Comment by PLCHome** [comment]
Same probem: warning State attribute definition missing for : liveseg with value : -1
iobroker.wled: v0.6.7
WLED 0.13.3 Toki Build 2208222

<html>
<body>


-- | -- | -- | --
wled.0 | 2022-10-10 19:57:08.339 | debug | Create_state called for : b4e62de93819._info.lm with value :
wled.0 | 2022-10-10 19:57:08.338 | debug | State created : lm : ""
**wled.0 | 2022-10-10 19:57:08.333 | warn | State attribute definition missing for : liveseg with value : -1**
wled.0 | 2022-10-10 19:57:08.332 | debug | Create_state called for : b4e62de93819._info.liveseg with value : -1
wled.0 | 2022-10-10 19:57:08.332 | debug | State created : liveseg : -1
wled.0 | 2022-10-10 19:57:08.328 | debug | Create_state called for : b4e62de93819._info.live with value : false
wled.0 | 2022-10-10 19:57:08.326 | debug | State created : live : false
wled.0 | 2022-10-10 19:57:08.321 | debug | Create_state called for : b4e62de93819._info.udpport with value : 21324
wled.0 | 2022-10-10 19:57:08.320 | debug | State created : udpport : 21324
wled.0 | 2022-10-10 19:57:08.316 | debug | Create_state called for : b4e62de93819._info.name with value : BAD
wled.0 | 2022-10-10 19:57:08.315 | debug | State created : name : "BAD"


</body>
</html>

**Comment by bernhaddl** [comment]
Same Problem here
ioBroker.wled v0.6.7
WLED 0.13.3

wled.0 | 2022-10-15 22:16:11.742 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-10-15 21:40:10.761 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-10-15 21:40:10.307 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-10-15 21:40:10.227 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-10-15 21:40:09.825 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-10-15 21:40:09.679 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-10-15 21:40:09.381 | warn | State attribute definition missing for : liveseg with value : -1

**Comment by Rushmed** [comment]
@DutchmanNL Any progress @this Topic?
Pls let me know if further help is needed!

**Comment by Blockmove** [comment]
Same thing here. After upgrading to WLED 0.13.3.
Adapterversion 0.6.7

**Comment by MarkSau** [comment]
Now we have one month later since last entry.

**Comment by Rushmed** [comment]
Hier noch ein LOG Auszug von heute Abend:
`<html>
<body>


wled.0 | 2022-12-16 23:07:44.990 | warn | State attribute definition missing for : liveseg with value : -1
-- | -- | -- | --
wled.0 | 2022-12-16 23:06:55.264 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:06:01.837 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:04:43.750 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:04:40.625 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:03:26.782 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:03:21.190 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:03:08.699 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:02:43.959 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:02:40.296 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 23:01:53.277 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:59:12.053 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:56:50.339 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:56:10.186 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:56:08.171 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:55:15.311 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:55:13.312 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:53:56.865 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:52:27.173 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:46:28.732 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:46:26.728 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:45:28.492 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:43:48.983 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:41:04.458 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:36:30.475 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:34:46.688 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:34:44.685 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:33:52.763 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:33:12.048 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:33:10.054 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:27:45.565 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:27:42.234 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:25:44.451 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:25:42.419 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:24:50.959 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:24:48.902 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:22:24.361 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:16:55.452 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:16:53.409 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:14:21.550 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:14:01.403 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:06:57.687 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:06:55.660 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:06:11.307 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:05:30.840 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 22:03:49.759 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:38.823 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:20.056 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:11.639 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:08.931 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:08.287 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:05.268 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:04.885 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:02.258 | warn | State attribute definition missing for : liveseg with value : -1
wled.0 | 2022-12-16 21:53:00.941 | warn | State attribute definition missing for : liveseg with value : -1


</body>
</html>`

Ich stell jetzt erstmal das Loglevel auf Error.

**Comment by trovanaffm** [comment]
Wurde im PR 471 gefixt.

**Comment by trovanaffm** [comment]
Im IOBroker Admin auf Adapter gehen. 
Expertenmodus Aktivieren, 
Installation von URL aktivieren, 
URL zum Github einfügen und installieren.

![image](https://user-images.githubusercontent.com/62116621/229367729-0789d073-caeb-43da-a9c1-2b293b9f5151.png)

**Comment by DutchmanNL** [comment]
fix released in v.0.7.0

**Comment by bernhaddl** [comment]
Since I installed WLED Version 0.14.0-b3 the problem is back ...
ioBroker WLED Version 0.7.0

**Comment by DutchmanNL** [comment]
> Since I installed WLED Version 0.14.0-b3 the problem is back ... ioBroker WLED Version 0.7.0
> 
> `State attribute definition missing for : set with value : 0`

ah ok that's a different one, set was not reported, please try to install from git issue should be solved by https://github.com/DrozmotiX/ioBroker.wled/commit/de8bd002b821e311b11d3cf7e94cf55287841afb

**Comment by bernhaddl** [comment]
Worked! 👍🏼
Thanks!

**Comment by DutchmanNL** [comment]
> Worked! 👍🏼
> Thanks!

danke, dan nehme ich das mit 0.7.1 mit :)

**Comment by DutchmanNL** [comment]
fixed in 0.7.1, available on latest and PR pending to updated stable : https://github.com/ioBroker/ioBroker.repositories/compare/master...DutchmanNL:ioBroker.repositories:patch-11

**Comment by bernhaddl** [comment]
Seit der WLED Version 0.14.0-b6 gibt es wieder eine neue Fehlermeldung im ioBroker:

`State attribute definition missing for : rgrp with value : 1`

**Comment by HaggardFFM** [comment]
> Seit der WLED Version 0.14.0-b6 gibt es wieder eine neue Fehlermeldung im ioBroker:
> 
> `State attribute definition missing for : rgrp with value : 1`

Ich habe das mal in die StateAttr.js eingefügt.
